// Customer Data

export type CustomerType = {
  id: string;
  userId: string;
  name: string;
  email: string;
  birthday: Date;
  gender: "male" | "female";
  address: string;
  totalTransaction: number;
  totalPurchase: number;
};

export const customersList: CustomerType[] = [
  {
    id: "CS1",
    userId: "user_001",
    name: "Alice Johnson",
    email: "alice.johnson@email.com",
    birthday: new Date("1990-05-14"),
    gender: "female",
    address: "123 Main St, New York, NY",
    totalTransaction: 15,
    totalPurchase: 1200,
  },
  {
    id: "CS2",
    userId: "user_002",
    name: "Bob Smith",
    email: "bob.smith@email.com",
    birthday: new Date("1985-07-22"),
    gender: "male",
    address: "456 Oak Ave, Los Angeles, CA",
    totalTransaction: 8,
    totalPurchase: 850,
  },
  {
    id: "CS3",
    userId: "user_003",
    name: "Charlie Brown",
    email: "charlie.brown@email.com",
    birthday: new Date("1992-11-30"),
    gender: "male",
    address: "789 Pine Rd, Chicago, IL",
    totalTransaction: 22,
    totalPurchase: 1900,
  },
  {
    id: "CS4",
    userId: "user_004",
    name: "Diana Clark",
    email: "diana.clark@email.com",
    birthday: new Date("1988-02-11"),
    gender: "female",
    address: "321 Maple Dr, Houston, TX",
    totalTransaction: 10,
    totalPurchase: 1300,
  },
  {
    id: "CS5",
    userId: "user_005",
    name: "Evan White",
    email: "evan.white@email.com",
    birthday: new Date("1995-08-04"),
    gender: "male",
    address: "654 Birch Ln, Miami, FL",
    totalTransaction: 5,
    totalPurchase: 550,
  },
  {
    id: "CS6",
    userId: "user_006",
    name: "Fiona Green",
    email: "fiona.green@email.com",
    birthday: new Date("1987-03-16"),
    gender: "female",
    address: "987 Cedar Blvd, Dallas, TX",
    totalTransaction: 18,
    totalPurchase: 1600,
  },
  {
    id: "CS7",
    userId: "user_007",
    name: "George Harris",
    email: "george.harris@email.com",
    birthday: new Date("1993-01-08"),
    gender: "male",
    address: "432 Elm St, San Francisco, CA",
    totalTransaction: 14,
    totalPurchase: 1450,
  },
  {
    id: "CS8",
    userId: "user_008",
    name: "Hannah Lewis",
    email: "hannah.lewis@email.com",
    birthday: new Date("1991-09-22"),
    gender: "female",
    address: "654 Spruce Dr, Seattle, WA",
    totalTransaction: 25,
    totalPurchase: 2200,
  },
  {
    id: "CS9",
    userId: "user_009",
    name: "Ian Walker",
    email: "ian.walker@email.com",
    birthday: new Date("1994-12-10"),
    gender: "male",
    address: "321 Redwood Ln, Denver, CO",
    totalTransaction: 11,
    totalPurchase: 1200,
  },
  {
    id: "CS10",
    userId: "user_010",
    name: "Julia Adams",
    email: "julia.adams@email.com",
    birthday: new Date("1982-05-03"),
    gender: "female",
    address: "876 Pine Ave, Austin, TX",
    totalTransaction: 17,
    totalPurchase: 1400,
  },
  {
    id: "CS11",
    userId: "user_011",
    name: "Kevin Scott",
    email: "kevin.scott@email.com",
    birthday: new Date("1990-02-15"),
    gender: "male",
    address: "654 Birch St, Phoenix, AZ",
    totalTransaction: 30,
    totalPurchase: 2500,
  },
  {
    id: "CS12",
    userId: "user_012",
    name: "Lily Harris",
    email: "lily.harris@email.com",
    birthday: new Date("1996-06-30"),
    gender: "female",
    address: "123 Oak Rd, San Diego, CA",
    totalTransaction: 13,
    totalPurchase: 1000,
  },
  {
    id: "CS13",
    userId: "user_013",
    name: "Mason Evans",
    email: "mason.evans@email.com",
    birthday: new Date("1989-04-18"),
    gender: "male",
    address: "345 Willow Ln, Portland, OR",
    totalTransaction: 20,
    totalPurchase: 1700,
  },
  {
    id: "CS14",
    userId: "user_014",
    name: "Nina Turner",
    email: "nina.turner@email.com",
    birthday: new Date("1994-08-09"),
    gender: "female",
    address: "567 Cedar Dr, Columbus, OH",
    totalTransaction: 22,
    totalPurchase: 1900,
  },
  {
    id: "CS15",
    userId: "user_015",
    name: "Oscar Allen",
    email: "oscar.allen@email.com",
    birthday: new Date("1983-12-25"),
    gender: "male",
    address: "678 Maple Ave, Boston, MA",
    totalTransaction: 8,
    totalPurchase: 600,
  },
  {
    id: "CS16",
    userId: "user_016",
    name: "Paula Wright",
    email: "paula.wright@email.com",
    birthday: new Date("1997-11-14"),
    gender: "female",
    address: "789 Birch Rd, Tampa, FL",
    totalTransaction: 6,
    totalPurchase: 750,
  },
  {
    id: "CS17",
    userId: "user_017",
    name: "Quincy Perez",
    email: "quincy.perez@email.com",
    birthday: new Date("1992-02-05"),
    gender: "male",
    address: "123 Oak Ln, Salt Lake City, UT",
    totalTransaction: 10,
    totalPurchase: 900,
  },
  {
    id: "CS18",
    userId: "user_018",
    name: "Rachel King",
    email: "rachel.king@email.com",
    birthday: new Date("1986-09-13"),
    gender: "female",
    address: "456 Cedar Blvd, Orlando, FL",
    totalTransaction: 5,
    totalPurchase: 300,
  },
  {
    id: "CS19",
    userId: "user_019",
    name: "Steve Clark",
    email: "steve.clark@email.com",
    birthday: new Date("1984-01-22"),
    gender: "male",
    address: "789 Maple St, Atlanta, GA",
    totalTransaction: 14,
    totalPurchase: 1350,
  },
  {
    id: "CS20",
    userId: "user_020",
    name: "Tina Mitchell",
    email: "tina.mitchell@email.com",
    birthday: new Date("1993-03-28"),
    gender: "female",
    address: "987 Spruce Ln, Raleigh, NC",
    totalTransaction: 17,
    totalPurchase: 1500,
  },
  {
    id: "CS21",
    userId: "user_021",
    name: "Uma Thompson",
    email: "uma.thompson@email.com",
    birthday: new Date("1995-04-12"),
    gender: "female",
    address: "321 Ash St, Charlotte, NC",
    totalTransaction: 14,
    totalPurchase: 1200,
  },
  {
    id: "CS22",
    userId: "user_022",
    name: "Vera Watson",
    email: "vera.watson@email.com",
    birthday: new Date("1991-07-19"),
    gender: "female",
    address: "654 Pine Ln, Phoenix, AZ",
    totalTransaction: 18,
    totalPurchase: 1500,
  },
  {
    id: "CS23",
    userId: "user_023",
    name: "William Harris",
    email: "william.harris@email.com",
    birthday: new Date("1988-03-04"),
    gender: "male",
    address: "987 Oak Blvd, Chicago, IL",
    totalTransaction: 20,
    totalPurchase: 1800,
  },
  {
    id: "CS24",
    userId: "user_024",
    name: "Xena Nelson",
    email: "xena.nelson@email.com",
    birthday: new Date("1990-06-25"),
    gender: "female",
    address: "123 Maple Rd, Las Vegas, NV",
    totalTransaction: 22,
    totalPurchase: 2100,
  },
  {
    id: "CS25",
    userId: "user_025",
    name: "Yara Clark",
    email: "yara.clark@email.com",
    birthday: new Date("1993-12-11"),
    gender: "female",
    address: "456 Birch St, Seattle, WA",
    totalTransaction: 15,
    totalPurchase: 1450,
  },
  {
    id: "CS26",
    userId: "user_026",
    name: "Zane Turner",
    email: "zane.turner@email.com",
    birthday: new Date("1987-09-05"),
    gender: "male",
    address: "789 Cedar Dr, Denver, CO",
    totalTransaction: 17,
    totalPurchase: 1600,
  },
  {
    id: "CS27",
    userId: "user_027",
    name: "Aaron Lee",
    email: "aaron.lee@email.com",
    birthday: new Date("1989-10-17"),
    gender: "male",
    address: "321 Elm St, San Francisco, CA",
    totalTransaction: 30,
    totalPurchase: 2600,
  },
  {
    id: "CS28",
    userId: "user_028",
    name: "Bella Martin",
    email: "bella.martin@email.com",
    birthday: new Date("1992-11-23"),
    gender: "female",
    address: "654 Oak Blvd, Houston, TX",
    totalTransaction: 12,
    totalPurchase: 1100,
  },
  {
    id: "CS29",
    userId: "user_029",
    name: "Charlie Davis",
    email: "charlie.davis@email.com",
    birthday: new Date("1996-02-14"),
    gender: "male",
    address: "987 Maple St, Boston, MA",
    totalTransaction: 20,
    totalPurchase: 1750,
  },
  {
    id: "CS30",
    userId: "user_030",
    name: "Diana Walker",
    email: "diana.walker@email.com",
    birthday: new Date("1994-05-22"),
    gender: "female",
    address: "123 Birch Ln, Atlanta, GA",
    totalTransaction: 28,
    totalPurchase: 2200,
  },
  {
    id: "CS31",
    userId: "user_031",
    name: "Ethan Young",
    email: "ethan.young@email.com",
    birthday: new Date("1986-12-01"),
    gender: "male",
    address: "456 Cedar Blvd, Miami, FL",
    totalTransaction: 9,
    totalPurchase: 900,
  },
  {
    id: "CS32",
    userId: "user_032",
    name: "Fayla Cooper",
    email: "fayla.cooper@email.com",
    birthday: new Date("1995-01-19"),
    gender: "female",
    address: "321 Ash Ave, Philadelphia, PA",
    totalTransaction: 13,
    totalPurchase: 1000,
  },
  {
    id: "CS33",
    userId: "user_033",
    name: "Gregory Allen",
    email: "gregory.allen@email.com",
    birthday: new Date("1987-08-29"),
    gender: "male",
    address: "654 Pine Rd, Orlando, FL",
    totalTransaction: 14,
    totalPurchase: 1300,
  },
  {
    id: "CS34",
    userId: "user_034",
    name: "Holly Scott",
    email: "holly.scott@email.com",
    birthday: new Date("1990-07-16"),
    gender: "female",
    address: "987 Maple Blvd, Dallas, TX",
    totalTransaction: 22,
    totalPurchase: 1900,
  },
  {
    id: "CS35",
    userId: "user_035",
    name: "Ivy Wilson",
    email: "ivy.wilson@email.com",
    birthday: new Date("1994-10-09"),
    gender: "female",
    address: "321 Pine Rd, Los Angeles, CA",
    totalTransaction: 10,
    totalPurchase: 850,
  },
  {
    id: "CS36",
    userId: "user_036",
    name: "Jake Anderson",
    email: "jake.anderson@email.com",
    birthday: new Date("1992-04-23"),
    gender: "male",
    address: "654 Cedar Ln, New York, NY",
    totalTransaction: 19,
    totalPurchase: 1700,
  },
  {
    id: "CS37",
    userId: "user_037",
    name: "Kara Moore",
    email: "kara.moore@email.com",
    birthday: new Date("1991-11-06"),
    gender: "female",
    address: "987 Birch Blvd, Chicago, IL",
    totalTransaction: 25,
    totalPurchase: 2200,
  },
  {
    id: "CS38",
    userId: "user_038",
    name: "Leo Hall",
    email: "leo.hall@email.com",
    birthday: new Date("1993-03-27"),
    gender: "male",
    address: "123 Cedar Rd, Seattle, WA",
    totalTransaction: 18,
    totalPurchase: 1600,
  },
  {
    id: "CS39",
    userId: "user_039",
    name: "Mia Foster",
    email: "mia.foster@email.com",
    birthday: new Date("1990-12-04"),
    gender: "female",
    address: "654 Oak Blvd, San Diego, CA",
    totalTransaction: 21,
    totalPurchase: 1850,
  },
  {
    id: "CS40",
    userId: "user_040",
    name: "Nathan Reed",
    email: "nathan.reed@email.com",
    birthday: new Date("1992-09-19"),
    gender: "male",
    address: "789 Maple Rd, Boston, MA",
    totalTransaction: 15,
    totalPurchase: 1300,
  },
];
