export type OrderType = {
  orderId: string;
  customerName: string;
  orderDate: string;
  status: "Pending" | "Processing" | "Completed" | "Cancelled";
  itemsOrdered: string;
  totalAmount: number;
  paymentStatus: "Paid" | "Unpaid" | "Refunded";
  deliveryStatus: "Shipped" | "In Transit" | "Delivered" | "Returned";
};

export const orderList: OrderType[] = [
  {
    orderId: "ORD1",
    customerName: "John Doe",
    orderDate: "2024-12-01",
    status: "Completed",
    itemsOrdered: "Laptop, Mouse, Keyboard",
    totalAmount: 1200.5,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD2",
    customerName: "Jane Smith",
    orderDate: "2024-12-02",
    status: "Processing",
    itemsOrdered: "Smartphone, Charger",
    totalAmount: 800.75,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD3",
    customerName: "Alice Johnson",
    orderDate: "2024-12-03",
    status: "Pending",
    itemsOrdered: "Headphones, USB Cable",
    totalAmount: 150.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD4",
    customerName: "Bob Brown",
    orderDate: "2024-12-04",
    status: "Completed",
    itemsOrdered: "Monitor, Webcam",
    totalAmount: 450.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD5",
    customerName: "Charlie Davis",
    orderDate: "2024-12-05",
    status: "Cancelled",
    itemsOrdered: "Laptop Stand",
    totalAmount: 45.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD6",
    customerName: "Emily Wilson",
    orderDate: "2024-12-06",
    status: "Pending",
    itemsOrdered: "Tablet, Stylus Pen",
    totalAmount: 350.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD7",
    customerName: "David Martinez",
    orderDate: "2024-12-07",
    status: "Completed",
    itemsOrdered: "Smartwatch, Charging Dock",
    totalAmount: 230.5,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD8",
    customerName: "Sophia Garcia",
    orderDate: "2024-12-08",
    status: "Processing",
    itemsOrdered: "Keyboard, Mouse Pad",
    totalAmount: 60.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD9",
    customerName: "Mason Lee",
    orderDate: "2024-12-09",
    status: "Completed",
    itemsOrdered: "Gaming Console",
    totalAmount: 500.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD10",
    customerName: "Olivia Harris",
    orderDate: "2024-12-10",
    status: "Pending",
    itemsOrdered: "Smartphone Case, Screen Protector",
    totalAmount: 35.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD11",
    customerName: "Lucas Robinson",
    orderDate: "2024-12-11",
    status: "Completed",
    itemsOrdered: "Laptop, Bag",
    totalAmount: 1100.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD12",
    customerName: "Avery Clark",
    orderDate: "2024-12-12",
    status: "Cancelled",
    itemsOrdered: "Smartwatch, Case",
    totalAmount: 300.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD13",
    customerName: "Liam Walker",
    orderDate: "2024-12-13",
    status: "Completed",
    itemsOrdered: "Phone, Charger, Earbuds",
    totalAmount: 900.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD14",
    customerName: "Ella Perez",
    orderDate: "2024-12-14",
    status: "Processing",
    itemsOrdered: "Bluetooth Speaker",
    totalAmount: 120.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD15",
    customerName: "Ethan Thomas",
    orderDate: "2024-12-15",
    status: "Pending",
    itemsOrdered: "Laptop Cooling Pad",
    totalAmount: 60.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD16",
    customerName: "Isabella Moore",
    orderDate: "2024-12-16",
    status: "Completed",
    itemsOrdered: "Camera, Lens",
    totalAmount: 800.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD17",
    customerName: "Mia Taylor",
    orderDate: "2024-12-17",
    status: "Cancelled",
    itemsOrdered: "Smartphone, Case",
    totalAmount: 320.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD18",
    customerName: "William Jackson",
    orderDate: "2024-12-18",
    status: "Completed",
    itemsOrdered: "Monitor, Keyboard",
    totalAmount: 400.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD19",
    customerName: "James White",
    orderDate: "2024-12-19",
    status: "Pending",
    itemsOrdered: "Phone Case, Screen Protector",
    totalAmount: 25.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD20",
    customerName: "Harper King",
    orderDate: "2024-12-20",
    status: "Processing",
    itemsOrdered: "Wireless Earbuds, Charger",
    totalAmount: 150.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },

  {
    orderId: "ORD21",
    customerName: "Amelia Carter",
    orderDate: "2024-12-21",
    status: "Completed",
    itemsOrdered: "Smartphone, Charger, Case",
    totalAmount: 650.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD22",
    customerName: "Benjamin Martinez",
    orderDate: "2024-12-22",
    status: "Processing",
    itemsOrdered: "Laptop, Mouse",
    totalAmount: 700.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD23",
    customerName: "Charlotte Anderson",
    orderDate: "2024-12-23",
    status: "Completed",
    itemsOrdered: "Smartwatch, Charging Dock",
    totalAmount: 250.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD24",
    customerName: "Daniel Garcia",
    orderDate: "2024-12-24",
    status: "Pending",
    itemsOrdered: "Headphones, USB Cable",
    totalAmount: 85.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD25",
    customerName: "Evelyn Lee",
    orderDate: "2024-12-25",
    status: "Completed",
    itemsOrdered: "Bluetooth Speaker",
    totalAmount: 150.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD26",
    customerName: "Finley Clark",
    orderDate: "2024-12-26",
    status: "Cancelled",
    itemsOrdered: "Camera, Lens",
    totalAmount: 450.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD27",
    customerName: "Grace King",
    orderDate: "2024-12-27",
    status: "Pending",
    itemsOrdered: "Tablet, Stylus Pen",
    totalAmount: 320.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD28",
    customerName: "Henry Walker",
    orderDate: "2024-12-28",
    status: "Completed",
    itemsOrdered: "Gaming Console, Controller",
    totalAmount: 550.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD29",
    customerName: "Ivy Scott",
    orderDate: "2024-12-29",
    status: "Processing",
    itemsOrdered: "Smartphone, Power Bank",
    totalAmount: 340.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD30",
    customerName: "Jackie Lewis",
    orderDate: "2024-12-30",
    status: "Completed",
    itemsOrdered: "Laptop, Bag",
    totalAmount: 1200.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD31",
    customerName: "Katherine Harris",
    orderDate: "2024-12-31",
    status: "Pending",
    itemsOrdered: "Smartwatch, Screen Protector",
    totalAmount: 220.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD32",
    customerName: "Liam Robinson",
    orderDate: "2025-01-01",
    status: "Completed",
    itemsOrdered: "Bluetooth Earbuds",
    totalAmount: 75.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD33",
    customerName: "Megan Green",
    orderDate: "2025-01-02",
    status: "Cancelled",
    itemsOrdered: "Wireless Mouse",
    totalAmount: 45.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD34",
    customerName: "Nathan Adams",
    orderDate: "2025-01-03",
    status: "Completed",
    itemsOrdered: "Phone Case, Screen Protector",
    totalAmount: 30.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD35",
    customerName: "Olivia Perez",
    orderDate: "2025-01-04",
    status: "Processing",
    itemsOrdered: "Monitor, Keyboard",
    totalAmount: 450.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD36",
    customerName: "Peyton Martin",
    orderDate: "2025-01-05",
    status: "Pending",
    itemsOrdered: "Laptop, Charger",
    totalAmount: 850.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD37",
    customerName: "Quinn Thompson",
    orderDate: "2025-01-06",
    status: "Completed",
    itemsOrdered: "Smartphone, Case",
    totalAmount: 550.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD38",
    customerName: "Rachel White",
    orderDate: "2025-01-07",
    status: "Processing",
    itemsOrdered: "Smartwatch, Charger",
    totalAmount: 250.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD39",
    customerName: "Samuel Clark",
    orderDate: "2025-01-08",
    status: "Cancelled",
    itemsOrdered: "Tablet, Cover",
    totalAmount: 300.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD40",
    customerName: "Tina Williams",
    orderDate: "2025-01-09",
    status: "Completed",
    itemsOrdered: "Laptop Stand, Mouse",
    totalAmount: 120.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD41",
    customerName: "Ursula Hall",
    orderDate: "2025-01-10",
    status: "Processing",
    itemsOrdered: "Camera, Tripod",
    totalAmount: 350.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD42",
    customerName: "Victor Allen",
    orderDate: "2025-01-11",
    status: "Pending",
    itemsOrdered: "Earbuds, Case",
    totalAmount: 75.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD43",
    customerName: "Wendy Scott",
    orderDate: "2025-01-12",
    status: "Completed",
    itemsOrdered: "Gaming Keyboard, Mouse Pad",
    totalAmount: 130.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD44",
    customerName: "Xander Young",
    orderDate: "2025-01-13",
    status: "Processing",
    itemsOrdered: "Smartphone, Headphones",
    totalAmount: 400.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD45",
    customerName: "Yasmine King",
    orderDate: "2025-01-14",
    status: "Completed",
    itemsOrdered: "Gaming Console, Games",
    totalAmount: 600.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD46",
    customerName: "Zane Wilson",
    orderDate: "2025-01-15",
    status: "Pending",
    itemsOrdered: "Laptop, Keyboard",
    totalAmount: 950.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
  {
    orderId: "ORD47",
    customerName: "Aiden Cooper",
    orderDate: "2025-01-16",
    status: "Completed",
    itemsOrdered: "Smartphone, Charger",
    totalAmount: 400.0,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
  },
  {
    orderId: "ORD48",
    customerName: "Bella Mitchell",
    orderDate: "2025-01-17",
    status: "Cancelled",
    itemsOrdered: "Smartwatch, Cover",
    totalAmount: 200.0,
    paymentStatus: "Refunded",
    deliveryStatus: "Returned",
  },
  {
    orderId: "ORD49",
    customerName: "Carter Edwards",
    orderDate: "2025-01-18",
    status: "Processing",
    itemsOrdered: "Laptop, Bag",
    totalAmount: 950.0,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
  },
  {
    orderId: "ORD50",
    customerName: "Diana Taylor",
    orderDate: "2025-01-19",
    status: "Pending",
    itemsOrdered: "Phone Case, Headphones",
    totalAmount: 100.0,
    paymentStatus: "Unpaid",
    deliveryStatus: "Shipped",
  },
];
